### ISSUE TITLE
WPF czy Console?

### ISSUE THREAD

**Issue by SirKOSA** [SirKOSA/Hotel-Transylwania#1]
### Witam współzałożycieli hotelu Transylwania!
**Czy jesteście chętni na odrobine zabawy z projektem?** Z Przemkiem wpadliśmy na pomysł żeby nasz projekt był nieco ładniejszy od konsolki. Wiec proponuję zrobić z tego projektu apke/okienko **(WPF)** albo zaprojektować jakiś ładniejszy interfejs z użyciem **html**. Troszkę więcej roboty, ale da się zrobić! Wsumie mamy 4 osoby w zespole.
Czekam na waszą opnię!

**Comment by Trzewik** [comment]
Popieram ten pomysł tych panów wyżej ;p

**Comment by jsonta** [comment]
To w sumie dobry pomysł. W Visualu można w miarę łatwo konstruować interfejsy okienkowe... tak przynajmniej było w Visual C# 2010, nie wiem jak w nowszych wersjach.

**Comment by jsonta** [comment]
W ogóle to trzeba pchnąć ten projekt do przodu, Panowie...
